theme: jekyll-theme-minimal

title: Data Visualization
short-title: Vis
course-number: CSC 54-844
semester: Fall
year: 2017

location: Olin 111

class-time: TR 2:30pm-3:45pm

instructor: Dr. Chad Stolper

instructor-email: stolperc at southwestern.edu

instructor-office: MBH 142B

office-hours: See Moodle or office door for listed office hours. You may also make appointments, or swing by my office if my door is open.

show_downloads: false